name: build
on:
  push:
    branches: [ main ]
  schedule:
    # Run weekly (* is a special character in YAML, so quote the string)
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout neovim
      uses: actions/checkout@v2
      with:
        repository: neovim/neovim
        path: repo

    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cd repo
        mkdir .deps
        cd .deps
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..\third-party
        cmake --build .
        cd ..
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=..\..\Neovim ..
        cmake --build .
        ninja
        ninja install

    - name: Zip
      shell: powershell
      run: Compress-Archive Neovim nvim-win64.zip

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: nvim-win64.zip