name: build
on:
  push:
    branches: [ main ]
  schedule:
    # Run weekly (* is a special character in YAML, so quote the string)
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout neovim-windows-nightly
      uses: actions/checkout@v2

    - name: Checkout neovim
      uses: actions/checkout@v2
      with:
        repository: neovim/neovim
        path: neovim

    - name: Build
      run: cmd.exe /C build.bat
